### ISSUE TITLE
Can't find packages on StackBlitz

### ISSUE THREAD

**Issue by splincode** [Angular-RU/angular-ngrx-starter#1]
It is necessary to take care of some packages in advance

![image](https://user-images.githubusercontent.com/12021443/41455129-b6facb9e-7084-11e8-8823-b1e25e527384.png)

**Comment by klimentru1986** [comment]
It`s problem with [tsconfig paths in StackBlitz](https://github.com/stackblitz/core/issues/220)

We can`t fix it.

You can clone or download project to your computer.

**Comment by merkuriy** [comment]
In [CodeSandbox](https://codesandbox.io) also have the this problem with custom tsconfig paths.
Example project: https://codesandbox.io/s/github/Angular-RU/angular-ngrx-starter
Issue: https://github.com/codesandbox/codesandbox-client/issues/807
